"""initial_schema_5_tables

Revision ID: 3f48a3dedd1c
Revises: 
Create Date: 2026-04-23 20:58:53.581377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3f48a3dedd1c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drug_knowledge_base',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('generic_name_ko', sa.String(length=200), nullable=False),
    sa.Column('generic_name_en', sa.String(length=200), nullable=False),
    sa.Column('drug_class', sa.String(length=200), nullable=False),
    sa.Column('indications', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('contraindications', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('standard_dosage', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dose_forms', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('strengths_available_mg', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('guideline_source', sa.Text(), nullable=False),
    sa.Column('guideline_year', sa.Integer(), nullable=False),
    sa.Column('guideline_url', sa.Text(), nullable=True),
    sa.Column('special_populations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('drug_interactions', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('monitoring_parameters', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('clinical_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drug_knowledge_base_generic_name_en'), 'drug_knowledge_base', ['generic_name_en'], unique=False)
    op.create_index(op.f('ix_drug_knowledge_base_generic_name_ko'), 'drug_knowledge_base', ['generic_name_ko'], unique=False)
    op.create_table('patient_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_code', sa.String(length=50), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=1), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('diseases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('lab_values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('allergies', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('current_medications', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('clinical_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_profiles_patient_code'), 'patient_profiles', ['patient_code'], unique=True)
    op.create_table('patient_lab_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('lab_values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_lab_history_patient_id'), 'patient_lab_history', ['patient_id'], unique=False)
    op.create_index(op.f('ix_patient_lab_history_recorded_at'), 'patient_lab_history', ['recorded_at'], unique=False)
    op.create_table('prescription_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('drug_id', sa.UUID(), nullable=False),
    sa.Column('recommended_generic_name_ko', sa.String(length=200), nullable=False),
    sa.Column('recommended_generic_name_en', sa.String(length=200), nullable=False),
    sa.Column('recommended_strength_mg', sa.Float(), nullable=True),
    sa.Column('recommended_dose_description', sa.Text(), nullable=False),
    sa.Column('recommended_frequency', sa.String(length=100), nullable=False),
    sa.Column('recommended_duration_days', sa.Integer(), nullable=True),
    sa.Column('clinical_rationale', sa.Text(), nullable=False),
    sa.Column('guideline_reference', sa.Text(), nullable=True),
    sa.Column('warnings', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('physician_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['drug_id'], ['drug_knowledge_base.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescription_logs_patient_id'), 'prescription_logs', ['patient_id'], unique=False)
    op.create_index(op.f('ix_prescription_logs_session_id'), 'prescription_logs', ['session_id'], unique=False)
    op.create_table('prescription_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prescription_log_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('feedback_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('affected_generic_ko', sa.String(length=200), nullable=False),
    sa.Column('affected_generic_en', sa.String(length=200), nullable=False),
    sa.Column('recorded_by', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ),
    sa.ForeignKeyConstraint(['prescription_log_id'], ['prescription_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescription_feedback_patient_id'), 'prescription_feedback', ['patient_id'], unique=False)
    op.create_index(op.f('ix_prescription_feedback_prescription_log_id'), 'prescription_feedback', ['prescription_log_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prescription_feedback_prescription_log_id'), table_name='prescription_feedback')
    op.drop_index(op.f('ix_prescription_feedback_patient_id'), table_name='prescription_feedback')
    op.drop_table('prescription_feedback')
    op.drop_index(op.f('ix_prescription_logs_session_id'), table_name='prescription_logs')
    op.drop_index(op.f('ix_prescription_logs_patient_id'), table_name='prescription_logs')
    op.drop_table('prescription_logs')
    op.drop_index(op.f('ix_patient_lab_history_recorded_at'), table_name='patient_lab_history')
    op.drop_index(op.f('ix_patient_lab_history_patient_id'), table_name='patient_lab_history')
    op.drop_table('patient_lab_history')
    op.drop_index(op.f('ix_patient_profiles_patient_code'), table_name='patient_profiles')
    op.drop_table('patient_profiles')
    op.drop_index(op.f('ix_drug_knowledge_base_generic_name_ko'), table_name='drug_knowledge_base')
    op.drop_index(op.f('ix_drug_knowledge_base_generic_name_en'), table_name='drug_knowledge_base')
    op.drop_table('drug_knowledge_base')
    # ### end Alembic commands ###
