"""add_lab_submissions

Revision ID: b844a1eadeb9
Revises: 3f48a3dedd1c
Create Date: 2026-05-02 10:45:43.925848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b844a1eadeb9'
down_revision: Union[str, None] = '3f48a3dedd1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lab_submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('photo_path', sa.Text(), nullable=True),
    sa.Column('parsed_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('is_parsed', sa.Boolean(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_submissions_patient_id'), 'lab_submissions', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lab_submissions_patient_id'), table_name='lab_submissions')
    op.drop_table('lab_submissions')
    # ### end Alembic commands ###
